---
version: "2.1"
services:
  sonarr:
    image: linuxserver/sonarr:${SONARR_VER}
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022 #optional
    volumes:
      - ./sonarr/data:/config
      - ./sonarr/tv:/tv
      - ./sonarr/dl-client:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:${RADARR_VER}
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022 #optional
    volumes:
      - ./radarr/data:/config
      - ./radarr/movies:/movies
      - ./radarr/dl-client:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sabnzbd:
    image: linuxserver/sabnzbd:${SABNZBD_VER}
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./sabnzbd/config:/config
      - ./sabnzbd/downloads:/downloads
      - ./sabnzbd/incomplete-downloads:/incomplete-downloads #optional
    ports:
      - 8080:8080
      - 9090:9090
    restart: unless-stopped

  organizr:
    image: linuxserver/organizr:${ORGANIZR_VER}
    container_name: organizr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./organizr/config:/config
    ports:
      - 9983:80
    restart: unless-stopped

  ombi:
    image: linuxserver/ombi:${OMBI_VER}
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - BASE_URL=/ombi #optional
    volumes:
      - ./ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped
  