---
version: "2.1"
services:
  ombi:
    image: linuxserver/ombi:${OMBI_VER}
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - BASE_URL=/ombi #optional
    volumes:
      - ./ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped