---
version: "2.1"
services:
  organizr:
    image: linuxserver/organizr:${ORGANIZR_VER}
    container_name: organizr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./organizr/config:/config
    ports:
      - 9983:80
    restart: unless-stopped