---
version: "2.1"
services:
  radarr:
    image: linuxserver/radarr:${RADARR_VER}
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022 #optional
    volumes:
      - ./radarr/data:/config
      - ./radarr/movies:/movies
      - ./radarr/dl-client:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped