---
version: "2.1"
services:
     sonarr:
       image: linuxserver/sonarr:${SONARR_VER}
       container_name: sonarr
       environment:
         - PUID=1000
         - PGID=1000
         - TZ=America/Chicago
         - UMASK_SET=022 #optional
       volumes:
         - ./sonarr/data:/config
         - ./sonarr/tv:/tv
         - ./sonarr/dl-client:/downloads
       ports:
         - 8989:8989
       restart: unless-stopped