---
version: "2.1"
services:
     sonarr:
       image: linuxserver/sonarr:${SONAR_VER}
       container_name: sonarr
       environment:
         - PUID=1000
         - PGID=1000
         - TZ=America/Chicago
         - UMASK_SET=022 #optional
     volumes:
         - /path/to/data:/config
         - /path/to/tvseries:/tv
         - /path/to/downloadclient-downloads:/downloads
     ports:
         - 8989:8989
     restart: unless-stopped